version: '3'
services:
  db:
    container_name: 'connthass-db'
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '33306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  api:
    container_name: 'connthass-api'
    build: ./api
    volumes:
      - ./api:/go/api
    ports:
      - '18888:8080'
    links:
      - db
